# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crossprod_rcpp <- function(A, B) {
    .Call('_htlgmm_crossprod_rcpp', PACKAGE = 'htlgmm', A, B)
}

prod_rcpp <- function(A, B) {
    .Call('_htlgmm_prod_rcpp', PACKAGE = 'htlgmm', A, B)
}

crossprodv_rcpp <- function(A, v) {
    .Call('_htlgmm_crossprodv_rcpp', PACKAGE = 'htlgmm', A, v)
}

prodv_rcpp <- function(A, v) {
    .Call('_htlgmm_prodv_rcpp', PACKAGE = 'htlgmm', A, v)
}

self_crossprod_rcpp <- function(A) {
    .Call('_htlgmm_self_crossprod_rcpp', PACKAGE = 'htlgmm', A)
}

expit_rcpp <- function(v) {
    .Call('_htlgmm_expit_rcpp', PACKAGE = 'htlgmm', v)
}

dexpit_rcpp <- function(v) {
    .Call('_htlgmm_dexpit_rcpp', PACKAGE = 'htlgmm', v)
}

addm_rcpp <- function(A, B) {
    .Call('_htlgmm_addm_rcpp', PACKAGE = 'htlgmm', A, B)
}

addv_rcpp <- function(u, v) {
    .Call('_htlgmm_addv_rcpp', PACKAGE = 'htlgmm', u, v)
}

timesv_rcpp <- function(u, v) {
    .Call('_htlgmm_timesv_rcpp', PACKAGE = 'htlgmm', u, v)
}

timesm_rcpp <- function(A, B) {
    .Call('_htlgmm_timesm_rcpp', PACKAGE = 'htlgmm', A, B)
}

