# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crossprod_rcpp <- function(A, B) {
    .Call('_htlgmm_crossprod_rcpp', PACKAGE = 'htlgmm', A, B)
}

prod_rcpp <- function(A, B) {
    .Call('_htlgmm_prod_rcpp', PACKAGE = 'htlgmm', A, B)
}

crossprodv_rcpp <- function(A, v) {
    .Call('_htlgmm_crossprodv_rcpp', PACKAGE = 'htlgmm', A, v)
}

prodv_rcpp <- function(A, v) {
    .Call('_htlgmm_prodv_rcpp', PACKAGE = 'htlgmm', A, v)
}

self_crossprod_rcpp <- function(A) {
    .Call('_htlgmm_self_crossprod_rcpp', PACKAGE = 'htlgmm', A)
}

expit_rcpp <- function(v) {
    .Call('_htlgmm_expit_rcpp', PACKAGE = 'htlgmm', v)
}

dexpit_rcpp <- function(v) {
    .Call('_htlgmm_dexpit_rcpp', PACKAGE = 'htlgmm', v)
}

timesv_rcpp <- function(u, v) {
    .Call('_htlgmm_timesv_rcpp', PACKAGE = 'htlgmm', u, v)
}

timesm_rcpp <- function(A, B) {
    .Call('_htlgmm_timesm_rcpp', PACKAGE = 'htlgmm', A, B)
}

square_rcpp <- function(mat) {
    .Call('_htlgmm_square_rcpp', PACKAGE = 'htlgmm', mat)
}

expitm_rcpp <- function(A) {
    .Call('_htlgmm_expitm_rcpp', PACKAGE = 'htlgmm', A)
}

sqrtchoinv_rcpp <- function(matrix) {
    .Call('_htlgmm_sqrtchoinv_rcpp', PACKAGE = 'htlgmm', matrix)
}

choinv_rcpp <- function(matrix) {
    .Call('_htlgmm_choinv_rcpp', PACKAGE = 'htlgmm', matrix)
}

sqrtcho_rcpp <- function(matrix) {
    .Call('_htlgmm_sqrtcho_rcpp', PACKAGE = 'htlgmm', matrix)
}

